# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        System\UserBundle\Entity\User:  sha512
    
    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_STAFF: ROLE_STAFF, ROLE_USER
        ROLE_MANAGER: ROLE_MANAGER, ROLE_USER
        ROLE_STANDARD: ROLE_STANDARD, ROLE_USER
        ROLE_CHILD: ROLE_CHILD, ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN, ROLE_USER, ROLE_STAFF, ROLE_CHILD
        ROLE_EXTERNAL: ROLE_EXTERNAL, ROLE_USER
        ROLE_SUPER_ADMIN:  [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH] 
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username   

    firewalls:
        main:    
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

                #csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true 
            remember_me:
                secret:   '%secret%'
                lifetime: 31 556 926 
                path: /
                domain: ~ 

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, role: ROLE_USER }

