# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    online_user:
        class: System\UserBundle\Service\OnlineUsers
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"
            templating: "@templating"
